version: '3.9'

services:
  core:
    image: node:20-alpine3.19
    restart: unless-stopped
    ports:
      - 80:5000
    env_file:
      - path: ./prisma.env
        required: true
      - path: ./.env
        required: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.4-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=measures
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
